# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "aiofiles" = super.buildPythonPackage rec {
    pname = "aiofiles";
    version = "0.8.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ca/e4/b78d049f7cc7ed053ddbfdd59b2dcc7bd387458e2c2869b602975685d65e/aiofiles-0.8.0-py3-none-any.whl";
      sha256 = "0dy935jqcv7zj5f8w30zmdkabrjnb375m04p10nrds995g13z5vs";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pybase16-builder" = super.buildPythonPackage rec {
    pname = "pybase16-builder";
    version = "0.2.8";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/cc/ad/cff784dd0e3c30be8d5e3d9aca2ea43368553c0e6e1553cea2bc3fe78df6/pybase16_builder-0.2.8-py3-none-any.whl";
      sha256 = "0jwd0g1s3zrpxr17mkx3zj380zgxpk7cdyc8kjsg6f3csdkk8cnm";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."aiofiles"
      self."pystache"
      self."pyyaml"
    ];
  };
  "pystache" = super.buildPythonPackage rec {
    pname = "pystache";
    version = "0.6.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/3f/e7/8750ba6c6101d6aa5ceeb20c013adf2c6f3554a12c71d75654b468404bfa/pystache-0.6.0.tar.gz";
      sha256 = "03a73ppf5vxnsk6az5ackvc0hp6xqv2f4hi1s5c4nk4s2jr95gwk";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [
      self."setuptools"
      self."wheel"
    ];
    propagatedBuildInputs = [];
  };
  "pyyaml" = super.buildPythonPackage rec {
    pname = "pyyaml";
    version = "6.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/36/2b/61d51a2c4f25ef062ae3f74576b01638bebad5e045f747ff12643df63844/PyYAML-6.0.tar.gz";
      sha256 = "18imkjacvpxfgg1lbpraqywx3j7hr5dv99d242byqvrh2jf53yv8";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
}
